name: Autograding - Reusable Workflow Exercise
on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  check-workflow-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify reusable workflow exists
        run: |
          if [[ ! -f .github/workflows/o-workflow.yml ]]; then
            echo "❌ Reusable workflow 'o-workflow.yml' not found"
            exit 1
          fi
          echo "✅ Reusable workflow exists"

      - name: Verify main workflow exists
        run: |
          if [[ ! -f .github/workflows/main-deploy.yml ]]; then
            echo "❌ Main workflow 'main-deploy.yml' not found"
            exit 1
          fi
          echo "✅ Main workflow exists"

      - name: Check workflow_call declaration
        run: |
          if ! grep -q "workflow_call" .github/workflows/o-workflow.yml; then
            echo "❌ Missing 'workflow_call' in o-workflow.yml"
            exit 1
          fi
          echo "✅ 'workflow_call' declared"

      - name: Check call to reusable workflow
        run: |
          if ! grep -q "uses: ./.github/workflows/o-workflow.yml" .github/workflows/main-deploy.yml; then
            echo "❌ Main workflow does not call the reusable workflow"
            exit 1
          fi
          echo "✅ Reusable workflow is called from main"

      - name: Check deploy job conditional logic
        run: |
          if ! grep -q "if:.*needs.call-build.outputs.build-status == 'success'" .github/workflows/main-deploy.yml; then
            echo "❌ Missing or incorrect conditional logic in deploy job"
            exit 1
          fi
          echo "✅ Conditional deploy logic is present"
